development:
  adapter: postgresql
  encoding: utf8
  database: scorely_project_development
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: scorely_project_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: scorely_project_production
  pool: 5
