default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: scorely_development

test:
  <<: *default
  database: scorely_test

production:
  <<: *default
  database: scorely_production
  username:
  password:
